// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/user.proto

package com.csse.grpc.generate;

public interface AllUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AllUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ResponseCode code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.ResponseCode code = 1;</code>
   * @return The code.
   */
  com.csse.grpc.generate.ResponseCode getCode();

  /**
   * <code>string msg = 2[json_name = "message"];</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2[json_name = "message"];</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>repeated .UserRequest data = 3;</code>
   */
  java.util.List<com.csse.grpc.generate.UserRequest> 
      getDataList();
  /**
   * <code>repeated .UserRequest data = 3;</code>
   */
  com.csse.grpc.generate.UserRequest getData(int index);
  /**
   * <code>repeated .UserRequest data = 3;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .UserRequest data = 3;</code>
   */
  java.util.List<? extends com.csse.grpc.generate.UserRequestOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .UserRequest data = 3;</code>
   */
  com.csse.grpc.generate.UserRequestOrBuilder getDataOrBuilder(
      int index);
}
