// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/user.proto

package com.csse.grpc.generate;

public interface PageParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PageParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *当前是第几页
   * </pre>
   *
   * <code>int64 pageNo = 1;</code>
   * @return The pageNo.
   */
  long getPageNo();

  /**
   * <pre>
   *每页多少条
   * </pre>
   *
   * <code>int64 pageSize = 2;</code>
   * @return The pageSize.
   */
  long getPageSize();
}
