// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/user.proto

package com.csse.grpc.generate;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ResponseCode code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.ResponseCode code = 1;</code>
   * @return The code.
   */
  com.csse.grpc.generate.ResponseCode getCode();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>.UserRequest data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.UserRequest data = 3;</code>
   * @return The data.
   */
  com.csse.grpc.generate.UserRequest getData();
  /**
   * <code>.UserRequest data = 3;</code>
   */
  com.csse.grpc.generate.UserRequestOrBuilder getDataOrBuilder();
}
