// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/user.proto

package com.csse.grpc.generate;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PageParam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PageParam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AllUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031src/main/proto/user.proto\032\033google/prot" +
      "obuf/empty.proto\"\211\001\n\013UserRequest\022\016\n\006user" +
      "Id\030\001 \001(\t\022\016\n\006userNo\030\002 \001(\t\022\020\n\010userName\030\003 \001" +
      "(\t\022\020\n\010userHead\030\004 \001(\t\022\020\n\010nickName\030\005 \001(\t\022\022" +
      "\n\npersonName\030\006 \001(\t\022\020\n\010pinyName\030\007 \001(\t\"P\n\010" +
      "Response\022\033\n\004code\030\001 \001(\0162\r.ResponseCode\022\013\n" +
      "\003msg\030\002 \001(\t\022\032\n\004data\030\003 \001(\0132\014.UserRequest\"-" +
      "\n\tPageParam\022\016\n\006pageNo\030\001 \001(\003\022\020\n\010pageSize\030" +
      "\002 \001(\003\"X\n\007AllUser\022\033\n\004code\030\001 \001(\0162\r.Respons" +
      "eCode\022\024\n\003msg\030\002 \001(\tR\007message\022\032\n\004data\030\003 \003(" +
      "\0132\014.UserRequest*4\n\014ResponseCode\022\013\n\007DEFAU" +
      "LT\020\000\022\t\n\004FAIL\020\364\003\022\014\n\007SUCCESS\020\310\0012\273\001\n\013UserSe" +
      "rvice\022$\n\007GetUser\022\014.UserRequest\032\t.Respons" +
      "e\"\000\022\'\n\nDeleteUser\022\014.UserRequest\032\t.Respon" +
      "se\"\000\022$\n\nGetUserAll\022\n.PageParam\032\010.AllUser" +
      "\"\000\0227\n\003Get\022\026.google.protobuf.Empty\032\026.goog" +
      "le.protobuf.Empty\"\000B(\n\026com.csse.grpc.gen" +
      "erateB\tUserProtoP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserRequest_descriptor,
        new java.lang.String[] { "UserId", "UserNo", "UserName", "UserHead", "NickName", "PersonName", "PinyName", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Code", "Msg", "Data", });
    internal_static_PageParam_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PageParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PageParam_descriptor,
        new java.lang.String[] { "PageNo", "PageSize", });
    internal_static_AllUser_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AllUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AllUser_descriptor,
        new java.lang.String[] { "Code", "Msg", "Data", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
