// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/user.proto

package com.csse.grpc.generate;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string userNo = 2;</code>
   * @return The userNo.
   */
  java.lang.String getUserNo();
  /**
   * <code>string userNo = 2;</code>
   * @return The bytes for userNo.
   */
  com.google.protobuf.ByteString
      getUserNoBytes();

  /**
   * <code>string userName = 3;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 3;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string userHead = 4;</code>
   * @return The userHead.
   */
  java.lang.String getUserHead();
  /**
   * <code>string userHead = 4;</code>
   * @return The bytes for userHead.
   */
  com.google.protobuf.ByteString
      getUserHeadBytes();

  /**
   * <code>string nickName = 5;</code>
   * @return The nickName.
   */
  java.lang.String getNickName();
  /**
   * <code>string nickName = 5;</code>
   * @return The bytes for nickName.
   */
  com.google.protobuf.ByteString
      getNickNameBytes();

  /**
   * <code>string personName = 6;</code>
   * @return The personName.
   */
  java.lang.String getPersonName();
  /**
   * <code>string personName = 6;</code>
   * @return The bytes for personName.
   */
  com.google.protobuf.ByteString
      getPersonNameBytes();

  /**
   * <code>string pinyName = 7;</code>
   * @return The pinyName.
   */
  java.lang.String getPinyName();
  /**
   * <code>string pinyName = 7;</code>
   * @return The bytes for pinyName.
   */
  com.google.protobuf.ByteString
      getPinyNameBytes();
}
